# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a2b1b8823ae2095e416f196f800b0953037e76de9c0996c8046884f4eb585cf0e8ea198d7003d8c32760686c47cb10e07d7d25d80944c6e69ffe6ce73a1c50b

test:
  secret_key_base: 6ed92b3aee5455e54e00e4f0080888287aa71b07b55bf8620bf998c11d7ba65a20cfe4fd1f4771cca2fd495b3c806aecb1ac670179967d701df572d51ee01139

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
